name: Continuous Integration

on:
  push:
    branches:
      - test

jobs:
  build:
    name: Basic Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Initialize submodules
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Lint
        run: deno lint
      - name: Format
        run: deno fmt
      - name: Test
        run: deno test
